In [1]:
%matplotlib inline
import os
import sys
import pandas as pd

In [2]:
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from src.features.build_features import load_data
from src.model.train import train_test

# Preface

This dataset involves predicting what category scientific papers fall into. There is a network of papers as well as the words used in the title.

## Load CORA Data

In [10]:
A, X, y, idx_train, idx_val, idx_test = load_data("../data/cora/", "cora", 140, 300, 1000)

Loading cora dataset...
Graph Info:
 Name: G
Type: Graph
Number of nodes: 2708
Number of edges: 5278
Average degree:   3.8981
Shape of A:  torch.Size([2708, 2708])

Shape of X:  torch.Size([2708, 1433])

Adjacency Matrix (A):
 tensor([[0.1667, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2500]])

Node Features Matrix (X):
 tensor([[-0.0771, -0.1111, -0.1629,  ..., -0.0471, -0.1568, -0.0667],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0471, -0.1568, -0.0667],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0471, -0.1568, -0.0667],
        ...,
        [-0.0771, -0.1111, -0.1629,  ..., -0.0471, -0.1568, -0.0667],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0471, -0.

# FCN (features only)

In [11]:
train_test(A, X, y, idx_train, idx_val, idx_test,
    no_cuda = False,
    seed = 42,
    epochs = 200,
    learning_rate = 0.0001,
    weight_decay = 5e-4,
    hidden_units = 256,
    dropout = 0.5,
    type = "FCN")

Epoch: 0010 loss_train: 1.6629 acc_train: 0.4714 loss_val: 1.8643 acc_val: 0.3100 time: 0.0035s
Epoch: 0020 loss_train: 1.4195 acc_train: 0.7071 loss_val: 1.8217 acc_val: 0.3500 time: 0.0030s
Epoch: 0030 loss_train: 1.1950 acc_train: 0.7929 loss_val: 1.7836 acc_val: 0.3733 time: 0.0033s
Epoch: 0040 loss_train: 1.0204 acc_train: 0.8429 loss_val: 1.7495 acc_val: 0.3800 time: 0.0030s
Epoch: 0050 loss_train: 0.8408 acc_train: 0.9286 loss_val: 1.7188 acc_val: 0.3967 time: 0.0032s
Epoch: 0060 loss_train: 0.6665 acc_train: 0.9714 loss_val: 1.6912 acc_val: 0.4033 time: 0.0029s
Epoch: 0070 loss_train: 0.6026 acc_train: 0.9643 loss_val: 1.6663 acc_val: 0.4333 time: 0.0036s
Epoch: 0080 loss_train: 0.4816 acc_train: 0.9857 loss_val: 1.6439 acc_val: 0.4567 time: 0.0042s
Epoch: 0090 loss_train: 0.4110 acc_train: 0.9786 loss_val: 1.6242 acc_val: 0.4667 time: 0.0039s
Epoch: 0100 loss_train: 0.3433 acc_train: 0.9857 loss_val: 1.6067 acc_val: 0.4867 time: 0.0037s
Epoch: 0110 loss_train: 0.3138 acc_train

# FCN (features and ad-hoc graph variables)

In [12]:
A1, X1, y1, idx_train, idx_val, idx_test = load_data("../data/cora/", "cora", 140, 300, 1000, True)

Loading cora dataset...
Graph Info:
 Name: G
Type: Graph
Number of nodes: 2708
Number of edges: 5278
Average degree:   3.8981
Shape of A:  torch.Size([2708, 2708])

Shape of X:  torch.Size([2708, 1435])

Adjacency Matrix (A):
 tensor([[0.1667, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.5000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.2000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.2000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.2000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.2500]])

Node Features Matrix (X):
 tensor([[-0.0771, -0.1111, -0.1629,  ..., -0.0667,  0.2108, -0.0845],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0667, -0.5544,  0.1031],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0667,  0.0195,  0.9141],
        ...,
        [-0.0771, -0.1111, -0.1629,  ..., -0.0667,  0.0195,  0.2772],
        [-0.0771, -0.1111, -0.1629,  ..., -0.0667,  0.

In [13]:
train_test(A1, X1, y1, idx_train, idx_val, idx_test,
    no_cuda = False,
    seed = 42,
    epochs = 200,
    learning_rate = 0.0001,
    weight_decay = 5e-4,
    hidden_units = 256,
    dropout = 0.5,
    type = "FCN")

Epoch: 0010 loss_train: 1.7022 acc_train: 0.4214 loss_val: 1.9171 acc_val: 0.2267 time: 0.0028s
Epoch: 0020 loss_train: 1.4837 acc_train: 0.5857 loss_val: 1.8703 acc_val: 0.2800 time: 0.0028s
Epoch: 0030 loss_train: 1.2065 acc_train: 0.8571 loss_val: 1.8283 acc_val: 0.3433 time: 0.0028s
Epoch: 0040 loss_train: 1.0163 acc_train: 0.8714 loss_val: 1.7906 acc_val: 0.3800 time: 0.0027s
Epoch: 0050 loss_train: 0.8579 acc_train: 0.9286 loss_val: 1.7568 acc_val: 0.4133 time: 0.0026s
Epoch: 0060 loss_train: 0.6881 acc_train: 0.9500 loss_val: 1.7266 acc_val: 0.4300 time: 0.0033s
Epoch: 0070 loss_train: 0.6184 acc_train: 0.9571 loss_val: 1.6994 acc_val: 0.4333 time: 0.0027s
Epoch: 0080 loss_train: 0.5103 acc_train: 0.9714 loss_val: 1.6751 acc_val: 0.4367 time: 0.0027s
Epoch: 0090 loss_train: 0.4243 acc_train: 0.9714 loss_val: 1.6533 acc_val: 0.4500 time: 0.0027s
Epoch: 0100 loss_train: 0.3670 acc_train: 0.9786 loss_val: 1.6342 acc_val: 0.4833 time: 0.0026s
Epoch: 0110 loss_train: 0.3245 acc_train

# node2vec (graph only)

node2vec = Node2Vec(G, dimensions=64, walk_length=30, num_walks=200, workers=4)

 Embed nodes

mod = node2vec.fit(window=10, min_count=1, batch_words=4)

Results 

Epoch: 0190 loss_train: 0.6387 acc_train: 0.6500 loss_val: 0.7089 acc_val: 0.5180 time: 0.0031s

Epoch: 0200 loss_train: 0.6372 acc_train: 0.6580 loss_val: 0.7102 acc_val: 0.5220 time: 0.0030s

Optimization Finished!
Total time elapsed: 0.6735s
Test set results: loss= 0.7037 accuracy= 0.5180

# node2vec (graph and features)

Epoch: 0190 loss_train: 0.6347 acc_train: 0.6420 loss_val: 0.7088 acc_val: 0.5095 time: 0.0045s

Epoch: 0200 loss_train: 0.6377 acc_train: 0.6420 loss_val: 0.7098 acc_val: 0.5095 time: 0.0030s

Optimization Finished!
Total time elapsed: 0.6197s
Test set results: loss= 0.7161 accuracy= 0.5093

# GCN (nodes and features)

In [18]:
train_test(A, X, y, idx_train, idx_val, idx_test,
    no_cuda = False,
    seed = 42,
    epochs = 500,
    learning_rate = 0.01,
    weight_decay = 5e-4,
    hidden_units = 256,
    dropout = 0.5,
    type = "GCN")

Epoch: 0010 loss_train: 1.8548 acc_train: 0.2929 loss_val: 1.8449 acc_val: 0.3667 time: 0.0085s
Epoch: 0020 loss_train: 1.8226 acc_train: 0.2929 loss_val: 1.8306 acc_val: 0.3667 time: 0.0077s
Epoch: 0030 loss_train: 1.8178 acc_train: 0.2929 loss_val: 1.8354 acc_val: 0.3667 time: 0.0121s
Epoch: 0040 loss_train: 1.8159 acc_train: 0.2929 loss_val: 1.8283 acc_val: 0.3667 time: 0.0096s
Epoch: 0050 loss_train: 1.8150 acc_train: 0.2929 loss_val: 1.8268 acc_val: 0.3667 time: 0.0083s
Epoch: 0060 loss_train: 1.8148 acc_train: 0.2929 loss_val: 1.8266 acc_val: 0.3667 time: 0.0082s
Epoch: 0070 loss_train: 1.8139 acc_train: 0.2929 loss_val: 1.8208 acc_val: 0.3667 time: 0.0078s
Epoch: 0080 loss_train: 1.7924 acc_train: 0.2929 loss_val: 1.8098 acc_val: 0.3633 time: 0.0082s
Epoch: 0090 loss_train: 1.7758 acc_train: 0.3571 loss_val: 1.8144 acc_val: 0.3467 time: 0.0102s
Epoch: 0100 loss_train: 1.7887 acc_train: 0.3214 loss_val: 1.8174 acc_val: 0.3567 time: 0.0099s
Epoch: 0110 loss_train: 1.7767 acc_train

# Discussion Questions

This node classification task is transductive as not all papers are classified in a category. Papers aren't always put into categories and there could be value in finding a proper one for them based on related or similar data in a citation network.

The Train-Test split can be done on the feature level then so that the full network can still be inputted into the model since there are essentially unlabled gaps in the network that we would want to classify.

*Summarize how each ML approach handles inductive graph learning (adding new nodes and edges at test-time). What computation has to occur at test-time?*

FCN(only features): This does fine with inductive graph learning because there is no link between the data points.

FCN (features and ad-hoc graph variables): This also does fine since there are features to carry predictions even if new data points don't have ad-hoc summarizations. I think at test time this graph input has to be imputed.

All graph inputted approaches: Need to use something like GraphSAGE that generates embeddings by "sampling and aggregating features from a node’s local neighborhood"